---

- name: Define root user
  hosts: all
  gather_facts: false
  connection: local
  
  tasks:
    - name: Define root user
      ansible.builtin.user:
        name: root
        group: root
        password: >-
          $y$j1T$TJGRZ9323Mj8xCeBIUYV4FwT$lUqchHN5ngN4bPxDYIj5LhN07rQfneSnoYe90VjyGsA
        uid: 0 
        update_password: on_create
      become: true
