---

- name: Demonstrate loop with extended syntax
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Loop with "new" syntax
      ansible.builtin.set_fact:
        my_var: >-
          {{ lookup( 'vars', ansible_loop_var ) }}
      loop: >-
        {{ query( 'sequence', 'start=0 stride=2 end=5' ) }}
      loop_control:
        loop_var: index
