---

- name: Demonstrate minimal loop
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Minimal loop
      ansible.builtin.set_fact:
        my_var: '{{ item }}'
      with_items: [2,4,6]
