---

- name: Circumvent nested loops by using product
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Loop on product
      ansible.builtin.set_fact:
        my_var:
          - "{{ lookup( 'vars', ansible_loop_var )[0] |int }}"
          - "{{ lookup( 'vars', ansible_loop_var )[1] |int }}"
      loop: >-
        {{ odd | product( even ) }}
      loop_control:
        loop_var: index
      vars:
        odd: >-
          {{ query( 'sequence', 'start=1 stride=2 end=5' ) }}
        even: >-
          {{ query( 'sequence', 'start=0 stride=2 end=5' ) }}
      register: loop_product
      tags:
        - loop_product

    - ansible.builtin.debug:
        var: loop_product
        verbosity: 2
      tags:
        - always
