---

# tee vault <<<$'---\npassword: mµP4szwörd\n'
# ansible-vault encrypt --ask-vault-password vault
# ansible-playbook 07_vault_01_mvp.yml -e @vault --ask-vault-password

- name: Demonstrate vaulted secret-file
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Show password
      ansible.builtin.debug:
        var: password

# ansible-vault decrypt --ask-vault-password vault
